name: Python CI

on: [push]

jobs:
  wyswietlenie_wersji:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Display Python version
        run: python --version

  test-pylinta:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdz repozytorium
        uses: actions/checkout@v2

      - name: Odpal Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: zainstaluj to co trzea
        run: pip install -r requirements.txt

      - name: uruchom pylint
        run: pylint app.py
