name: Python package

on: [push]

jobs:
  build:
  
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
        run: |
          python --version

          pytest
