name: Python Cl

on: [push, pull_request]

jobs:
  wersja_pythona:
  runs-on: ubuntu-latest
  
  steps:
    -name: Odpalanie python
    uses: actions/setup-python@v2
    with: 
      python-version: 3.x
    
    -name: Wyświetl wersje python
    run: python --version
  
  pylint-test:
    runs-on: ubuntu-latest
    
    steps:
      -name: Sprawdz repozytorium
      uses: actions/checkout@v2
      
      -name: Odpalanie python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
      
      -name: zleznosci
      run: pip install -r requirements.txt
      
      -name: Run Pylint
      run: pylint app.py
